### ISSUE TITLE
AnswerMediaSection::AnswerMediaSection  has a problem!

### ISSUE THREAD

**Issue by jessonliu** [versatica/libmediasoupclient#71] opened 2020-01-15 10:09 UTC
MediaSection.cpp

function AnswerMediaSection::AnswerMediaSection

```c++
if (mimeType == "video/vp8" || mimeType == "video/vp9" || mimeType == "video/h264" || mimeType == "video/h265")
{
	auto videoGoogleStartBitrateIt = codecOptions->find("videoGoogleStartBitrate");
	if (videoGoogleStartBitrateIt != codecOptions->end() && videoGoogleStartBitrateIt->is_number_integer())
	{
		auto startBitrate = videoGoogleStartBitrateIt->get<uint32_t>();
		offerCodec["parameters"]["x-google-start-bitrate"] = startBitrate;
		// maybe you shorld add one line
		codecParameters["x-google-start-bitrate"] = startBitrate;

	}

	auto videoGoogleMaxBitrateIt = codecOptions->find("videoGoogleMaxBitrate");
	if (videoGoogleMaxBitrateIt != codecOptions->end() && videoGoogleMaxBitrateIt->is_number_integer())
	{
		auto maxBitrate = videoGoogleMaxBitrateIt->get<uint32_t>();
		offerCodec["parameters"]["x-google-max-bitrate"] = maxBitrate;
		// add one line
		codecParameters["x-google-max-bitrate"] = maxBitrate;

	}

	auto videoGoogleMinBitrateIt = codecOptions->find("videoGoogleMinBitrate");
	if (videoGoogleMinBitrateIt != codecOptions->end() && videoGoogleMinBitrateIt->is_number_integer())
	{
		auto minBitrate = videoGoogleMinBitrateIt->get<uint32_t>();
		offerCodec["parameters"]["x-google-min-bitrate"] = minBitrate;
		// add one line
		codecParameters["x-google-min-bitrate"] = minBitrate;

	}
}
```

**Comment by ibc** [comment] 2020-01-15 10:20
Please, describe what the problem is.

**Comment by jessonliu** [comment] 2020-01-16 06:07
when i create Producer, Set the codecOption to {"videoGoogleStartBitrate":4000},
I found it didn't work out, 
I'm in the function std::pair<std::string, nlohmann::json> SendHandler::Send  print the answer, 
`this->remoteSdp->Send(offerMediaObject, mediaSectionIdx["reuseMid"], sendingRtpParameters,
		  this->sendingRemoteRtpParametersByKind[track->kind()], codecOptions);`

		`auto answer = this->remoteSdp->GetSdp();`
        
`std::cout << answer << std::endl;`

x-google-start-bitrate value is 1000, not 4000! 
That is to say, setting codecOptions is invalid when creating the producer

**Comment by ibc** [comment] 2020-01-16 12:34
Thanks, fixed in https://github.com/versatica/libmediasoupclient/commit/07f160f9541b453f77742413cceb707241642edf.

However no new version will be released yet since we are in the middle of a refactor. You can use `v3` branch at your risk.

**Closed as completed** 2020-01-16 12:33 UTC
